export interface Type {
  name: string;
  typeTagSrc: string;
  typeIconSrc: string;
  num: number;
  teraTagSrc: string;
  bgColor: string;
}

export const attackAbilities: string[] = [
  //at
  'なし',
  'ARシステム',
  'アナライズ',
  'いろめがね',
  'いわはこび',
  'うるおいボイス',
  'エレキスキン',
  'おやこあい',
  'かがくへんかガス',
  'かたいツメ',
  'かたやぶり',
  'がんじょうあご',
  'きもったま',
  'きれあじ',
  'クォークチャージ',
  'げきりゅう',
  'こだいかっせい',
  'ごりむちゅう',
  'こんじょう',
  'サンパワー',
  'しんがん',
  'しんりょく',
  'すいほう',
  'スカイスキン',
  'すてみ',
  'スナイパー',
  'すなのちから',
  'すりぬけ',
  'スロースタート',
  'そうだいしょう',
  'ダークオーラ',
  'ターボブレイズ',
  'ちからずく',
  'ちからもち',
  'てきおうりょく',
  'テクニシャン',
  'てつのこぶし',
  'テラボルテージ',
  'とうそうしん',
  'どくぼうそう',
  'トランジスタ',
  'ねつぼうそう',
  'ノーマルスキン',
  'はがねつかい',
  'はがねのせいしん',
  'バッテリー',
  'ハドロンエンジン',
  'はりきり',
  'はりこみ',
  'パワースポット',
  'パンクロック',
  'ばんけん',
  'フェアリーオーラ',
  'フェアリースキン',
  'プラス',
  'フラワーギフト',
  'フリーズスキン',
  'ブレインフォース',
  'ヘヴィメタル',
  'マイナス',
  'むしのしらせ',
  'メガランチャー',
  'もうか',
  'もらいび',
  'ヨガパワー',
  'よわき',
  'ライトメタル',
  'りゅうのあぎと',
  'わざわいのうつわ',
  'わざわいのおふだ',
  'わざわいのたま',
  'わざわいのつるぎ',
];

export const defenceAbilities: string[] = [
  //df
  'なし',
  'あついしぼう',
  'オーラブレイク',
  'カブトアーマー',
  'かんそうはだ',
  'きよめのしお',
  'クォークチャージ',
  'くさのけがわ',
  'こおりのりんぷん',
  'こだいかっせい',
  'シェルアーマー',
  'すいほう',
  'たいねつ',
  'テラスシェル',
  'てんねん',
  'ハードロック',
  'パンクロック',
  'ファーコート',
  'ファントムガード',
  'フィルター',
  'ふしぎなうろこ',
  'ふゆう',
  'フラワーギフト',
  'プリズムアーマー',
  'フレンドガード',
  'ヘヴィメタル',
  'ぼうじん',
  'マルチスケイル',
  'もふもふ',
  'ライトメタル',
  'わざわいのうつわ',
  'わざわいのおふだ',
  'わざわいのたま',
  'わざわいのつるぎ',
];

export const typeInterface: Type[] = [
  {
    name: '非選択',
    typeTagSrc: '/images/types/not_selected.png',
    typeIconSrc: '/images/types/bef_teras.png',
    num: 0,
    teraTagSrc: '/images/types/bef_tera_img.png',
    bgColor: '#a1abb3',
  },
  {
    name: 'ノーマル',
    typeTagSrc: '/images/types/nomaru_tag.png',
    typeIconSrc: '/images/types/noma_tera.png',
    num: 1,
    teraTagSrc: '/images/types/nomaru_tera_img.png',
    bgColor: '#a1abb3',
  },
  {
    name: 'みず',
    typeTagSrc: '/images/types/mizu_tag.png',
    typeIconSrc: '/images/types/mizu_tera.png',
    num: 2,
    teraTagSrc: '/images/types/mizu_tera_img.png',
    bgColor: '#3f73cf',
  },
  {
    name: 'ほのお',
    typeTagSrc: '/images/types/hono_tag.png',
    typeIconSrc: '/images/types/hono_tera.png',
    num: 3,
    teraTagSrc: '/images/types/hono_tera_img.png',
    bgColor: '#c3423d',
  },
  {
    name: 'かくとう',
    typeTagSrc: '/images/types/kakuto_tag.png',
    typeIconSrc: '/images/types/kakuto_tera.png',
    num: 4,
    teraTagSrc: '/images/types/kakuto_tera_img.png',
    bgColor: '#d07a2c',
  },
  {
    name: 'ひこう',
    typeTagSrc: '/images/types/hiko_tag.png',
    typeIconSrc: '/images/types/hiko_tera.png',
    num: 5,
    teraTagSrc: '/images/types/hiko_tera_img.png',
    bgColor: '#82a8d7',
  },
  {
    name: 'いわ',
    typeTagSrc: '/images/types/iwa_tag.png',
    typeIconSrc: '/images/types/iwa_tera.png',
    num: 6,
    teraTagSrc: '/images/types/iwa_tera_img.png',
    bgColor: '#a7a380',
  },
  {
    name: 'じめん',
    typeTagSrc: '/images/types/jimen_tag.png',
    typeIconSrc: '/images/types/jimen_tera.png',
    num: 7,
    teraTagSrc: '/images/types/jimen_tera_img.png',
    bgColor: '#794d28',
  },
  {
    name: 'こおり',
    typeTagSrc: '/images/types/kori_tag.png',
    typeIconSrc: '/images/types/kori_tera.png',
    num: 8,
    teraTagSrc: '/images/types/kori_tera_img.png',
    bgColor: '#60bccc',
  },
  {
    name: 'くさ',
    typeTagSrc: '/images/types/kusa_tag.png',
    typeIconSrc: '/images/types/kusa_tera.png',
    num: 9,
    teraTagSrc: '/images/types/kusa_tera_img.png',
    bgColor: '#57a139',
  },
  {
    name: 'むし',
    typeTagSrc: '/images/types/mushi_tag.png',
    typeIconSrc: '/images/types/mushi_tera.png',
    num: 10,
    teraTagSrc: '/images/types/mushi_tera_img.png',
    bgColor: '#8d9936',
  },
  {
    name: 'エスパー',
    typeTagSrc: '/images/types/esupa_tag.png',
    typeIconSrc: '/images/types/esupa_tera.png',
    num: 11,
    teraTagSrc: '/images/types/esupa_tera_img.png',
    bgColor: '#c65177',
  },
  {
    name: 'どく',
    typeTagSrc: '/images/types/doku_tag.png',
    typeIconSrc: '/images/types/doku_tera.png',
    num: 12,
    teraTagSrc: '/images/types/doku_tera_img.png',
    bgColor: '#864ebe',
  },
  {
    name: 'でんき',
    typeTagSrc: '/images/types/denki_tag.png',
    typeIconSrc: '/images/types/denki_tera.png',
    num: 13,
    teraTagSrc: '/images/types/denki_tera_img.png',
    bgColor: '#e5bf41',
  },
  {
    name: 'あく',
    typeTagSrc: '/images/types/aku_tag.png',
    typeIconSrc: '/images/types/aku_tera.png',
    num: 14,
    teraTagSrc: '/images/types/aku_tera_img.png',
    bgColor: '#473834',
  },
  {
    name: 'はがね',
    typeTagSrc: '/images/types/hagane_tag.png',
    typeIconSrc: '/images/types/hagane_tera.png',
    num: 15,
    teraTagSrc: '/images/types/hagane_tera_img.png',
    bgColor: '#71a0b6',
  },
  {
    name: 'ドラゴン',
    typeTagSrc: '/images/types/doragon_tag.png',
    typeIconSrc: '/images/types/doragon_tera.png',
    num: 16,
    teraTagSrc: '/images/types/doragon_tera_img.png',
    bgColor: '#4c59ca',
  },
  {
    name: 'ゴースト',
    typeTagSrc: '/images/types/gosuto_tag.png',
    typeIconSrc: '/images/types/gosuto_tera.png',
    num: 17,
    teraTagSrc: '/images/types/gosuto_tera_img.png',
    bgColor: '#67376b',
  },
  {
    name: 'フェアリー',
    typeTagSrc: '/images/types/feari_tag.png',
    typeIconSrc: '/images/types/feari_tera.png',
    num: 18,
    teraTagSrc: '/images/types/feari_tera_img.png',
    bgColor: '#e667e6',
  },
  {
    name: 'ステラ',
    typeTagSrc: '/images/types/stella_tag.png',
    typeIconSrc: '/images/types/stcheck.png',
    num: 19,
    teraTagSrc: '/images/types/stella_tera_img.png',
    bgColor: '#a1abb3',
  },
];

export interface Poke {
  id: number;
  name: string;
  src: string;
  types: Type[];
  hp: number;
  attack: number;
  defence: number;
  specialAttack: number;
  specialDefence: number;
  speed: number;
  abilities: string[];
  weight: number;
  anotherName: string;
  rank: number;
  skill1: string;
  skill2: string;
  skill3: string;
  skill4: string;
  skill5: string;
}

export const pokes: Poke[] = [
  {
    id: 987,
    name: 'ハバタクカミ',
    src: '/images/poke_image/poke0987.png',
    types: [typeInterface[17], typeInterface[18]],
    hp: 55,
    attack: 55,
    defence: 55,
    specialAttack: 135,
    specialDefence: 135,
    speed: 135,
    abilities: ['こだいかっせい'],
    weight: 4,
    anotherName: 'はばたくかみ',
    rank: 1000,
    skill1: 'ムーンフォース',
    skill2: 'シャドーボール',
    skill3: 'マジカルフレイム',
    skill4: 'パワージェム',
    skill5: 'たたりめ',
  },
  {
    id: 1002,
    name: 'パオジアン',
    src: '/images/poke_image/poke01002.png',
    types: [typeInterface[14], typeInterface[8]],
    hp: 80,
    attack: 120,
    defence: 80,
    specialAttack: 90,
    specialDefence: 65,
    speed: 135,
    abilities: ['わざわいのつるぎ'],
    weight: 152.0,
    anotherName: 'ぱおじあん',
    rank: 1000,
    skill1: 'つららおとし',
    skill2: 'ふいうち',
    skill3: 'せいなるつるぎ',
    skill4: 'こおりのつぶて',
    skill5: 'テラバースト',
  },
];
